### ISSUE TITLE
Problem with handler.retry in jaxon.core.js:2465 in version 4.0.4

### ISSUE THREAD

**Issue by sdaeges** [jaxon-php/jaxon-js#28]
Hello once again,

I've just upgraded to jaxon-js version 4.0.4 and I might have found a problem:

TypeError: handler.retry is not a function
    at self.waitFor [as func] (jaxon.core.js:2465:25)
    at self.call (jaxon.core.js:1227:24)
    at execute (jaxon.core.js:1171:21)
    at processCommand (jaxon.core.js:1183:13)
    at self.processCommands (jaxon.core.js:1208:18)
    at self.jsonProcessor [as responseProcessor] (jaxon.core.js:1814:21)
    at self.received (jaxon.core.js:1852:25)
    at oRequest.responseHandler (jaxon.core.js:1532:21)

I would have liked to offer a solution for this one, but I am a i bit stumped to be honest.

Regards,

Sascha

**Comment by sdaeges** [comment]
Slight addition:

handler is this at this point in the code.

![image](https://github.com/user-attachments/assets/9ded78f5-42bc-41ec-a351-d757f37aeed6)

The retry-function seems to be undefined.

**Comment by feuzeu** [comment]
Fixed in release https://github.com/jaxon-php/jaxon-js/releases/tag/v4.0.5.
